import {
  Home,
  Users,
  Grid,
  FileText,
  BookOpen,
  Calendar,
  Clock,
  BarChart,
  Bell,
  Search,
  Plus,
  Send,
  Bot,
  X,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  Mail,
  Star,
  Check,
  Info,
  AlertTriangle,
  Upload,
  Video,
  Pencil,
  Eye,
  TrendingUp,
  Settings,
  LogOut,
  GraduationCap,
  ArrowRight
} from "lucide-react";

const icons = {
  home: Home,
  scholars: Users,
  grid: Grid,
  file: FileText,
  book: BookOpen,
  cal: Calendar,
  users: Users,
  clock: Clock,
  bar: BarChart,
  bell: Bell,
  search: Search,
  plus: Plus,
  send: Send,
  bot: Bot,
  x: X,
  chevD: ChevronDown,
  chevU: ChevronUp,
  chevL: ChevronLeft,
  mail: Mail,
  star: Star,
  check: Check,
  info: Info,
  warn: AlertTriangle,
  upload: Upload,
  video: Video,
  pencil: Pencil,
  eye: Eye,
  trend: TrendingUp,
  cog: Settings,
  logout: LogOut,
  grad: GraduationCap,
  arrowR: ArrowRight
};

const Icon = ({ name, size = 18, color = "currentColor", sw = 1.8 }) => {
  const LucideIcon = icons[name] || Home;
  return <LucideIcon size={size} color={color} strokeWidth={sw} />;
};

export default Icon;